//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.City = new HashSet<City>();
        }
    
        public int CountryID { get; set; }
        public string CountryName { get; set; }
        public string Continent { get; set; }
        public Nullable<int> CountryRating { get; set; }
    
        public virtual ICollection<City> City { get; set; }
    }
}
